name: aitest
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pip:
    - ninja
    - imageio
    - PyOpenGL
    - glfw
    - xatlas
    - gdown
    - git+https://github.com/NVlabs/nvdiffrast/
    - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
