name: aitest
dependencies:
  - python=3.9
  - pytorch=1.10.1
  - torchvision=0.11.2
  - torchaudio=0.10.1
  - cudatoolkit=10.2
  - pip:
    - ninja
    - imageio
    - PyOpenGL
    - glfw
    - xatlas
    - gdown
    - git+https://github.com/NVlabs/nvdiffrast/
    - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
